#:schema node_modules/wrangler/config-schema.json
name = "rss"
main = "src/index.js"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat"]
send_email = [{ name = "email", destination_address = "benkarstens@web.de" }]

[observability]
enabled = true

[vars]
FEEDS = [
	"https://thephd.dev/feed.xml",
	"https://ciechanow.ski/atom.xml",
	"http://radar.spacebar.org/f/a/weblog/rss/1",
]
PREV_TIMESTAMP = 0

[triggers]
crons = ["0 0 * * *"]
