#:schema node_modules/wrangler/config-schema.json
name = "rss"
main = "src/index.js"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

[observability]
enabled = true

[triggers]
crons = ["0 * * * *"]

[vars]
FEEDS = [
	"https://thephd.dev/feed.xml",
	"https://ciechanow.ski/atom.xml",
	"http://radar.spacebar.org/f/a/weblog/rss/1",
]

[[send_email]]
name = "email"
destination_address = "benkarstens@web.de"

[[kv_namespaces]]
binding = "kv"
id = "8e096049d2d94b2f872427efdf41b559"
